[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "https://tarsasozz.netlify.com"
  to = "https://tarsasozz.blog"
  status = 301
  force = true
